# Codedeploy 설정 파일

version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/build/

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
      - location: scripts/beforeInstall.bash
        runas: ec2-user
  AfterInstall:
      - location: scripts/afterInstall.bash
        runas: ec2-user
# 로컬의 파일을 받아오기 전에(BeforeInstall) 실행할 스크립트를 지정합니다.
# 로컬의 파일을 받아온 다음에(AfterInstall) 실행할 스크립트를 지정합니다.
