name: PR Test
 
on:
  push:
    branches: [ cicd/25 ] # master branch에 PR을 보낼 때 실행
 
jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:   
        image: mysql:5.7  
        env:   
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: monkpentdb_test
        ports:
          - 3306:3306
        options: >- 
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

      redis:
        image: redis
        ports:
          - 6379:6379
          
    steps:
      - uses: actions/checkout@v2
 
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
#       - name: Set up MySQL
#         run: |
#           sudo /etc/init.d/mysql start
#           mysql -e 'CREATE DATABASE monkpentdb;' -u test -p test
 
      # Gradle wrapper 파일 실행 권한주기
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
 
      # Gradle test를 실행한다
      - name: Test with Gradle
        run: ./gradlew --info test
        
      # 테스트 후 Result를 보기위해 Publish Unit Test Results step 추가
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }}  # 테스트가 실패하여도 Report를 보기 위해 `always`로 설정
        with:
          files: build/test-results/**/*.xml
